### ISSUE TITLE
Change templates

### ISSUE THREAD

**Issue by MiguelArmendariz** [joshjg/vscode-generate-react-component#3]
I'm starting to learn react,
I've found a way to work without using the css modules but I want to keep using your extension,
it says it's easy to change templates but i can't find where I can change them.

**Comment by darotar** [comment]
Hi, I guess, you need define new path to template in your vscode user settings

"generate-react-component.componentTemplatePath": "./blablabla"

Like that

And create structure like in default template, just without modules

**Comment by pungggi** [comment]
here is the default template for components for example > https://github.com/joshjg/vscode-generate-react-component/tree/master/component_template
